### ISSUE TITLE
Get no such file for entrypoint

### ISSUE THREAD

**Issue by rbcrack** [weslambert/velociraptor-docker#13]
Hi 

Getting this error 

velociraptor  | exec /entrypoint: no such file or directory

The file is in the same folder where I pulled the git

**Comment by weslambert** [comment]
I just tried this and it worked fine for me. What kind of OS are you using?

Are you using `docker-compose/docker compose`?

**Comment by jonod8698** [comment]
Same here. Fresh Ubuntu 20.04.5 LTS server or Photon OS v4.

Using the prebuilt image from docker hub works fine. Uncomment that line as a temp fix.

![image](https://user-images.githubusercontent.com/51128479/197391876-98d56acd-71dc-4d85-9489-53f8f6def3d0.png)

**Comment by jef84142** [comment]
run this command then reclone the repo
>>> git config --global core.autocrlf false

**Comment by skhero** [comment]
If you are using m1 mac, add --platform linux/amd64 to from in dockerfile
I solved the same problem like that.
