### ISSUE TITLE
Unable to parse PEM when running container with environment variables 

### ISSUE THREAD

**Issue by dgilmore82** [weslambert/velociraptor-docker#20]
When we build our image, we use the following command:
`docker build -t velociraptor:local .`

which will then build the image with the following docker commands:

**Start with a blank Ubuntu 22 image**
FROM https://[blank]-ubuntu:22.04-7

 **Add yq, for manipulating yaml**
ADD https://[blank]/v4.34.2/yq_linux_amd64 /usr/bin/yq

 **Make it executable**
RUN ["chmod", "+x", "/usr/bin/yq"]

 **Add a user for velociraptor to run as**
RUN ["/usr/sbin/adduser", "--system", "--shell", "/bin/bash", "--disabled-password", "velociraptor"]

 **Create a directory for data, writeable by the velociraptor user**
RUN ["install", "-d", "-o", "velociraptor", "-m", "755", "/data"]

 **Retrieve the binary from repo and place it at /velociraptor**
ADD https://{blank}/github.com-releases/Velocidex/velociraptor/releases/download/v0.6.9/velociraptor-v0.6.9-linux-amd64 /velociraptor

 **Make it executable**
RUN ["chmod", "+x", "/velociraptor"]

 **Add a configuration file**
ADD server.config.yaml /server.config.yaml

 **Add a startup script which can prepare the configuration and launch the app**
ADD entrypoint /entrypoint

**Everything after this line happens as the 'velociraptor' user**
USER velociraptor

 **Set the default command to run to be the startup script**
CMD ["/entrypoint"]

Here is the entrypoint file:
#!/bin/bash
set -eu

cp /server.config.yaml /dev/shm/server.config.yaml

 **Use yq to perform environment variable substitution in the configuration file**
yq -i '.Client.server_urls[0] = strenv(server_url)' /dev/shm/server.config.yaml
yq -i '.Client.ca_certificate = strenv(client_ca_certificate)' /dev/shm/server.config.yaml
yq -i '.Client.nonce = strenv(client_nonce)' /dev/shm/server.config.yaml
yq -i '.API.hostname = strenv(api_hostname)' /dev/shm/server.config.yaml
yq -i '.API.bind_port = env(api_bind_port)' /dev/shm/server.config.yaml
yq -i '.GUI.bind_port = env(gui_bind_port)' /dev/shm/server.config.yaml
yq -i '.GUI.gw_certificate = strenv(gui_gw_certificate)' /dev/shm/server.config.yaml
yq -i '.GUI.gw_private_key = strenv(gui_gw_key)' /dev/shm/server.config.yaml
yq -i '.GUI.authenticator.oauth_client_id = strenv(gui_authenticator_oauth_client_id)' /dev/shm/server.config.yaml
yq -i '.GUI.authenticator.oauth_client_secret = strenv(gui_authenticator_oauth_client_secret)' /dev/shm/server.config.yaml
yq -i '.GUI.authenticator.tenant = strenv(gui_authenticator_tenant)' /dev/shm/server.config.yaml
yq -i '.CA.private_key = strenv(ca_private_key)' /dev/shm/server.config.yaml
yq -i '.GUI.gw_private_key = strenv(gui_gw_key)' /dev/shm/server.config.yaml
yq -i '.Frontend.hostname = env(frontend_hostname)' /dev/shm/server.config.yaml
yq -i '.Frontend.bind_port = env(frontend_bind_port)' /dev/shm/server.config.yaml
yq -i '.Frontend.certificate = strenv(frontend_certificate)' /dev/shm/server.config.yaml
yq -i '.Frontend.private_key = strenv(frontend_key)' /dev/shm/server.config.yaml
yq -i '.obfuscation_nonce = strenv(obfuscation_nonce)' /dev/shm/server.config.yaml
yq -i '.Monitoring.bind_port = env(monitoring_bind_port)' /dev/shm/server.config.yaml

 Start Velociraptor frontend
/velociraptor --config /dev/shm/server.config.yaml frontend -v

The following files are in the same location as the entrypoint and docker file:
* `client_ca.crt`
* `gw.crt`
* `gw.key`
* `ca.key`
* `frontend.crt`
* `frontend.key`

This is the docker command we are using:

`docker run --rm -it \
    -v "$(pwd)/velociraptor-data:/data" \
    --env-file env \
    -e "client_ca_certificate=$(< client_ca.crt)" \
    -e "gui_gw_certificate=$(< gw.crt)" \
    -e "gui_gw_key=$(< gw.key)" \
    -e "ca_private_key=$(< ca.key)" \
    -e "frontend_certificate=$(< frontend.crt)" \
    -e "frontend_key=$(< frontend.key)" \
    -p 38001 -p 32443 -p 38003 \
    velociraptor:local
`

This is the error message we are getting:
`velociraptor: error: frontend: starting frontend: Unable to parse PEM`

Really sorry for the long post but any guidance on this would be greatly appreciated.

Thanks!!

**Comment by weslambert** [comment]
No worries. I appreciate the amount of detail. I will take a look and get back to you.

**Comment by dgilmore82** [comment]
This can be closed. The issue was white spaces. Thanks aging for the assistance!!

**Comment by weslambert** [comment]
Sorry, I got tied up and completely forgot about this issue. I'm glad to hear you were able to resolve it, though! 😄
