### ISSUE TITLE
Difference between velociraptor-docker and so-velociraptor

### ISSUE THREAD

**Issue by john-mathew-itt** [weslambert/velociraptor-docker#22]
Hi Wes,

Thank you for this image. I was curious to know what is the difference between this dicker image and so-velociraptor image. I notice that this image is newer that so-velociraptor. I have been using so-velociraptor image in my SO instance, since this has latest features, can I use this image with SO?

Thanks,
John M.

**Comment by weslambert** [comment]
The entrypoint for the securityonion-velociraptor image is slightly different, so this image might not work with Security Onion, however, I should be able to update the other one and you should be able to continue using it.

**Comment by john-mathew-itt** [comment]
Thanks Wes, would really appreciate that.

Regards,
John Mathew.

________________________________

**Comment by john-mathew-itt** [comment]
Is there anyway I can help? @weslambert

**Comment by weslambert** [comment]
Things have just been busy lately 😅.  I just pushed a new image that should include 0.7.0. Please let me know if you have any issues.
