### ISSUE TITLE
velociraptor: error: config client: Configuration Client.server_urls must end with /

### ISSUE THREAD

**Issue by joejsullivan** [weslambert/velociraptor-docker#23]
Hi Wes - 
I'm attempting to redeploy. I messed up my whole docker deploy under Portainer. I initially did have this image (which is fantastic, btw) deployed without issue. I get the error:

velociraptor: error: config client: Configuration Client.server_urls must end with /

Below is my docker-compose file as well as the .env file I am importing. I'm not sure what is being referred to here, the only URI I can identify is the VELOX_SERVER_URL which does end with a /.

Any clues?
Thanks,
Joe

version: '3'

volumes:
  ubuntu-opt:

services:
  velociraptor:
    container_name: velociraptor
    image: wlambert/velociraptor
    volumes:
      - /ubuntu-opt/velo:/velociraptor
    environment:
      - VELOX_USER=${VELOX_USER}
      - VELOX_PASSWORD=${VELOX_PASSWORD}
      - VELOX_ROLE=${VELOX_ROLE}
      - VELOX_SERVER_URL=${VELOX_SERVER_URL}
      - VELOX_FRONTEND_HOSTNAME=${VELOX_FRONTEND_HOSTNAME}
      - TZ=America/Chicago
    ports:
      - "8002:8000"
      - "8001:8001"
      - "8889:8889"
    restart: unless-stopped

VELOX_USER=admin
VELOX_PASSWORD=a_password
VELOX_ROLE=administrator
VELOX_SERVER_URL=https://VelociraptorServer.tld.com:8002/
VELOX_FRONTEND_HOSTNAME=VelociraptorServer.tld.com

**Comment by joejsullivan** [comment]
I got it sorted. I had created a server side mount, - /ubuntu-opt/velo:/velociraptor
Once I manually removed /ubuntu-opt/velo, the error cleared up. I used a GPO to replace the clients YML file.

Thanks!

Joe

**Comment by D3vil0p3r** [comment]
This issue is still present:
```
velociraptor: error: config show: Configuration Client.server_urls must end with /
```
It is caused by the entrypoint.sh at
```bash
if [ ! -f server.config.yaml ]; then
	./velociraptor config generate > server.config.yaml --merge '{"Frontend":{"public_path":"'$PUBLIC_PATH'", "hostname":"'$VELOX_FRONTEND_HOSTNAME'"},"API":{"bind_address":"'$BIND_ADDRESS'"},"GUI":{"bind_address":"'$BIND_ADDRESS'"},"Monitoring":{"bind_address":"'$BIND_ADDRESS'"},"Logging":{"output_directory":"'$LOG_DIR'","separate_logs_per_component":true},"Client":{"server_urls":["'$VELOX_SERVER_URL'"],"use_self_signed_ssl":true}, "Datastore":{"location":"'$DATASTORE_LOCATION'", "filestore_directory":"'$FILESTORE_DIRECTORY'"}}'
        #sed -i "s#https://localhost:8000/#$VELOX_CLIENT_URL#" server.config.yaml
	sed -i 's#/tmp/velociraptor#.#'g server.config.yaml
	./velociraptor --config server.config.yaml user add $VELOX_USER $VELOX_PASSWORD --role $VELOX_ROLE
fi
```
in particular on:
```bash
"Client":{"server_urls":["'$VELOX_SERVER_URL'"],
```
@weslambert can you please fix it?

To reproduce it, just clone your repository and try to replace your `.env` content by:
```
VELOX_PASSWORD=changeme
VELOX_USER=admin
VELOX_ROLE=administrator
VELOX_FRONTEND_HOSTNAME=localhost
VELOX_SERVER_URL=https://localhost:8000/
```
