### ISSUE TITLE
Build Offline Collector function doesn't seem to work

### ISSUE THREAD

**Issue by alecisec** [weslambert/velociraptor-docker#3]
It appears there's some issue with the checks that look for the binaries to add the config to, initially I found the /opt/velociraptor folders weren't being populated (but they were created) so I took this part of the Dockerfile and ran it in the container to re-download them, but the process still doesn't work (the Artifact shows only Server.Utils.CreateCollector and no 'Uploaded files'

**Comment by weslambert** [comment]
Hi @alecisec,

I'll have to take a look at this -- what version of the server does it show for you?

**Comment by alecisec** [comment]
I'm not sure where to check that - this is image ID 35ee24b588db 
the error is just 'Collection did not upload files'

**Comment by alecisec** [comment]
I think part of the issue is that the binaries are being destroyed somehow - in a similar fashion if I'm to terminate the container it fails to restart (the check for binaries fails)

```Starting velociraptor ... done
Attaching to velociraptor
velociraptor    | mv: cannot stat '/opt/velociraptor/mac/velociraptor_client': No such file or directory
velociraptor exited with code 1```

**Comment by alecisec** [comment]
Here's a better play-by-play - this is from a clean git pull to running and checking the folders

```
ec2-user >docker-compose up -d
Creating velociraptor ... done
ec2-user >docker ps
CONTAINER ID        IMAGE                             COMMAND             CREATED             STATUS              PORTS                                                     NAMES
6d6b3e77e4b3        velociraptordocker_velociraptor   "/entrypoint"       5 seconds ago       Up 4 seconds        0.0.0.0:8000-8001->8000-8001/tcp, 0.0.0.0:443->8889/tcp   velociraptor
ec2-user >docker exec -it 6d6b3e77e4b3 ls /opt/velociraptor/windows
ec2-user >docker exec -it 6d6b3e77e4b3 ls /opt/velociraptor/mac
ec2-user >docker exec -it 6d6b3e77e4b3 ls /opt/velociraptor/linux
velociraptor
ec2-user >
```

**Comment by weslambert** [comment]
Thanks for the feedback.  I think I need to clean up how the binaries are handled on a rebuild/up/down.  I started this project really as a quick example of how to stand up Velociraptor before the `gui` option was available, so I probably need to go through and tidy up some things for times when there will be persistence.
