### ISSUE TITLE
Update Docker Image

### ISSUE THREAD

**Issue by weslambert** [weslambert/velociraptor-docker#9]
Need to update the base Docker image to Ubuntu 20.04 or newer. 

@xboarder56,  I noticed you recently updated the version for Ubuntu in a forked repo. Have you had good results with 20.04, and were you planning to submit a PR?

**Comment by Xboarder56** [comment]
In the process of testing it a bit and was planning on submitting a PR if works correctly.

**Comment by weslambert** [comment]
Sounds good, thanks!

**Comment by Xboarder56** [comment]
@weslambert, Just confirmed it's all good with some additional testing and a fresh agent deploy without any issues. Just submitted the PR.

**Comment by weslambert** [comment]
Thanks!

**Comment by weslambert** [comment]
Addressed with: https://github.com/weslambert/velociraptor-docker/pull/10
